name: AZenith

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - ".github/scripts/**"
      - "manager/**"
      - "jni/**"
      - "tweakfls/**"
      - "mainfiles/**"
      - "preloadbin/**"
      - "thermalcore/**"
      - "azenithApplist.json"
      - "version"
      - "version_type"

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    name: Build AZenith
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      
      - name: Verify Module
        run: bash .github/scripts/verify.sh
  
      - name: NDK Setup
        uses: nttld/setup-ndk@v1.5.0
        with:
          ndk-version: r29

      - name: Build AZenith JNI
        run: ndk-build

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: temurin

      - name: Build Manager APK
        working-directory: ./manager
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleRelease
        env:
          KS_PWD: ${{ secrets.KEYSTORE_PASSWORD }}
                    
      - name: Compile Flashable Zip
        id: compileZip
        run: bash .github/scripts/compile_zip.sh

      - name: Upload To Telegram
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TITLE: AZenith
        run: |
          if [ -n "$CHAT_ID" ] && [ -n "$BOT_TOKEN" ]; then
            export VERSION=$(git rev-list --count HEAD)
            bash .github/scripts/telebot.sh "${{ steps.compileZip.outputs.zipName }}"
          else
            echo "Telegram bot token or chatid is undefined!"
            exit 1
          fi

      - name: Prepare Artifact
        run: |
          mkdir -p extracted
          unzip "${{ steps.compileZip.outputs.zipName }}" -d extracted

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.compileZip.outputs.artifactName }}
          path: extracted/
